---
- name: Run the playbook tasks on the localhost from the /vagrant folder
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    groupname: samurai
    username: samurai

  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present

    - name: Ensure samurai user is present
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ groupname }},sudo"
        password: "$1$XF.06J/n$A1G6zX5AF33pQQOTcH0Ix."
        shell: /bin/bash
        state: present

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - nginx
          - vim
          - curl
          - unzip
          - php-fpm
          - nano
          - python3
          - python3-pip
          - python-is-python3
          - openjdk-17-jre
          - net-tools
        state: present

    - name: Install Python Docker module
      ansible.builtin.pip:
        name: docker
        executable: /usr/bin/pip3

    - name: Create directory /home/ss/code
      command: mkdir -p /home/ss/code
      become: yes  # If you need sudo privileges