---
- name: Run the playbook tasks on the localhost from the /vagrant folder
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    groupname: 52pickup
    username: example123!

  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ groupname }}"
        state: present

    - name: Ensure samurai user is present
      ansible.builtin.user:
        name: "{{ username }}"
        groups: "{{ groupname }},sudo"
        password: "$1$XF.06J/n$A1G6zX5AF33pQQOTcH0Ix."
        shell: /bin/bash
        state: present

    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - gnupg
        state: present
        update_cache: yes

    - name: Install additional packages
      ansible.builtin.apt:
        name:
          - nginx
          - vim
          - unzip
          - php-fpm
          - nano
          - python3
          - python3-pip
          - python-is-python3
          - openjdk-17-jre
          - net-tools
          - make 
          - build-essential 
          - libssl-dev 
          - zlib1g-dev 
          - libbz2-dev 
          - libreadline-dev 
          - libsqlite3-dev 
          - wget 
          - curl 
          - llvm 
          - libncurses5-dev 
          - libncursesw5-dev 
          - xz-utils 
          - tk-dev 
          - libffi-dev 
          - liblzma-dev    
          - python3-openssl
          
        state: present

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Configure environment variables for pyenv
      blockinfile:
        path: /home/52pickup/.profile"
        block: |
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init --path)"
          eval "$(pyenv virtualenv-init -)"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        create: yes

    - name: Apply profile changes
      shell: source /home/52pickup/.profile
      args:
        executable: /bin/bash

    - name: Add Pyenv
      shell: |
        cd /home/52pickup
        curl https://pyenv.run | bash
      become: yes