---
- name: Run the playbook tasks on the localhost from the /vagrant folder
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    groupname: 52pickup
    username: example123!

  tasks:
    - name: Create directory /home/52pickup/code
      command: mkdir -p /home/52pickup/code
      become: yes  # If you need sudo privileges

    - name: Change perms on code to 52pickup
      command: chown 52pickup:52pickup -R /home/52pickup/code
      become: yes  # If you need sudo privileges

    - name: Pull Juice Shop Container # https://hub.docker.com/r/bkimminich/juice-shop
      command: docker pull bkimminich/juice-shop
      become: yes  # If you need sudo privileges

    - name: webgoat 
      command: docker pull webgoat/webgoat #https://github.com/WebGoat/WebGoat
      become: yes

    - name: OWASP top 10 vuln API setup # https://github.com/erev0s/VAmPI
      command: docker pull erev0s/vampi
      become: yes

    - name: Wrong Secrets # https://github.com/OWASP/wrongsecrets
      command: docker pull jeroenwillemsen/wrongsecrets:latest-no-vault
      become: yes

    - name: dvwa # https://github.com/digininja/dvwa
      shell: |
        cd /home/52pickup/code
        git clone https://github.com/digininja/dvwa
        cd /home/52pickup/code/dvwa
        sed -i 's/127.0.0.1:4280:80/0.0.0.0:4280:80/g' /home/52pickup/code/dvwa/compose.yml #replace 127.0.0.1 with 0.0.0.0 thanks grok!    
        docker build --tag dvwa .
      become: yes

    - name: musashi-js # https://github.com/SamuraiWTF/musashi-js
      shell: |
        cd /home/52pickup/code
        git clone https://github.com/SamuraiWTF/musashi-js
        cd /home/52pickup/code/musashi-js
        docker build --tag musashi-js .
      become: yes

    # - name: Start Juice Shop Container # https://hub.docker.com/r/bkimminich/juice-shop
    #   command: docker run -d -p 3000:3000 bkimminich/juice-shop
    #   become: yes  # If you need sudo privileges

    # - name: Start OWASP top 10 vuln API setup # https://github.com/erev0s/VAmPI
    #   command: docker run -d -p 5000:5000 erev0s/vampi:latest
    #   become: yes  # If you need sudo privileges

    # - name: Start DVWA # https://github.com/digininja/DVWA
    #   shell: |
    #     cd /home/52pickup/code
    #     git clone https://github.com/digininja/dvwa
    #     cd dvwa
    #     docker-compose up -d
    #   become: yes

      # root@ubuntu2204:/home/52pickup# ps aux | grep docker
      # root         991  0.9  2.2 2191440 90848 ?       52pickupl  Feb22   0:11 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
      # root       22534  0.0  0.1  12956  4760 tty1     S+   00:09   0:00 sudo docker compose up
      # root       22535  0.0  0.0  12956   672 pts/0    52pickup   00:09   0:00 sudo docker compose up
      # root       22536  0.0  0.6 1773156 25008 pts/0   Sl+  00:09   0:00 docker compose up

      #####################################################################
      # KILL off this proce52pickup if for some reason the website isn't coming up
      # Browse using Safari if the Chrome / Edge scripts not working
      #####################################################################

      # root       22550  0.0  0.6 727956 25256 pts/0    Sl+  00:09   0:00 /usr/local/lib/docker/cli-plugins/docker-compose compose up

      #####################################################################
      # root       22889  0.0  0.0   6020  1996 pts/2    S+   00:11   0:00 grep --color=auto docker
      # root@ubuntu2204:/home/52pickup# kill -9 22550
      # root@ubuntu2204:/home/52pickup# ps aux | grep docker
      # root         991  0.9  2.2 2191440 91024 ?       52pickupl  Feb22   0:11 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
      # root       23044  0.0  0.0 1671180 4004 ?        Sl   00:12   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4280 -container-ip 172.18.0.3 -container-port 80 -use-listen-fd
      # root       23124  0.0  0.0   6020  2000 pts/2    S+   00:12   0:00 grep --color=auto docker
      # root@ubuntu2204:/home/52pickup# 


      #https://github.com/OWASP/wrongsecrets


    # - name: Echo listeners
    #   command: netstat -tuln | grep LISTEN
    #   become: yes